// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1VbgfOlapqvkF_VA1dOdVjFBDXRyl7NY',
    appId: '1:10071706183:web:1badbf5d9bc4b05d82bf62',
    messagingSenderId: '10071706183',
    projectId: 'iiitbh-54e3c',
    authDomain: 'iiitbh-54e3c.firebaseapp.com',
    storageBucket: 'iiitbh-54e3c.appspot.com',
    measurementId: 'G-JBKXLG9SBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxcDuVWyNL3wOMVs0GbrckDqnuVsWyjCs',
    appId: '1:10071706183:android:e9673d467179759982bf62',
    messagingSenderId: '10071706183',
    projectId: 'iiitbh-54e3c',
    storageBucket: 'iiitbh-54e3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoVNHVvJvwY88xYv3Gw04CYui0KLUqa-U',
    appId: '1:10071706183:ios:0a04da4245e1654b82bf62',
    messagingSenderId: '10071706183',
    projectId: 'iiitbh-54e3c',
    storageBucket: 'iiitbh-54e3c.appspot.com',
    iosBundleId: 'com.example.collegeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoVNHVvJvwY88xYv3Gw04CYui0KLUqa-U',
    appId: '1:10071706183:ios:8417e13ad63fff8182bf62',
    messagingSenderId: '10071706183',
    projectId: 'iiitbh-54e3c',
    storageBucket: 'iiitbh-54e3c.appspot.com',
    iosBundleId: 'com.example.collegeapp.RunnerTests',
  );
}
